version: "3.9"
services:
  postgresql_db:
    image: postgres:latest
    container_name: postgresql-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgresql_db_data:
  pgadmin_data: