"""add workspace and task tables and rls and roles

Revision ID: c37496d89102
Revises: d1d6fa09521f
Create Date: 2026-06-04 20:04:20.829922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.helpers.helpers import read_secret
# revision identifiers, used by Alembic.
revision: str = 'c37496d89102'
down_revision: Union[str, Sequence[str], None] = 'd1d6fa09521f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    #========== ROLES ====================
    fastapi_password = read_secret("POSTGRES_PASSWORD")
    op.execute(f"""
               DO $$ 
               BEGIN
                IF NOT EXISTS ( SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                    CREATE ROLE authenticated;
                END IF;
               END
               $$
            """)
    op.execute(f"""
               DO $$
               BEGIN
                    IF NOT EXISTS ( SELECT 1 FROM pg_roles WHERE rolname =  'fastapi_user') THEN
                        CREATE ROLE fastapi_user WITH LOGIN PASSWORD '{fastapi_password}';
                    END IF;
                END
                $$
            """)
   
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID of the workspace (primary key)'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='The name of the workspace'),
    sa.Column('desciption', sa.String(length=100), nullable=False, comment='The description of the workspace'),
    sa.Column('owner_id', sa.Uuid(), nullable=False, comment='The owner of the workspace'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the workspace was first created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When the workspace was updated'),
    sa.ForeignKeyConstraint(['owner_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='ID of Task'),
    sa.Column('title', sa.String(length=30), nullable=False, comment='The title of the task'),
    sa.Column('description', sa.String(length=30), nullable=True, comment='Task description'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='Status of the task.'),
    sa.Column('workspace_id', sa.Uuid(), nullable=False, comment='What workspace the task belong in'),
    sa.Column('assignee_id', sa.Uuid(), nullable=False, comment='Who the task is assigned to'),
    sa.Column('created_by', sa.Uuid(), nullable=False, comment='Who created the task'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the task was first created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When the task was updated'),
    sa.ForeignKeyConstraint(['assignee_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Workspace memebr id'),
    sa.Column('workspace_id', sa.Uuid(), nullable=False, comment='ID of the workspace the memebrs belong to'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='The ID of the user'),
    sa.Column('role', sa.String(length=30), server_default='admin', nullable=False, comment='The role of the member'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='when the memebr joined the workspace'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Updated time of memeber'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    op.add_column('auth_credentials', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('auth_credentials', sa.Column('last_login', sa.DateTime(timezone=True), nullable=False, comment="User's last login attempt"))
    op.alter_column('auth_credentials', 'user_id',
               existing_type=sa.UUID(),
               comment='Id of the user',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('auth_credentials', 'email',
               existing_type=sa.VARCHAR(length=30),
               comment='The email of the user',
               existing_nullable=False)
    op.alter_column('auth_credentials', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               comment="User's password",
               existing_nullable=False)
    op.alter_column('auth_credentials', 'role',
               existing_type=sa.VARCHAR(length=10),
               comment='The role of the user',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('auth_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the user was first created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the user was updated',
               existing_nullable=False)
    op.drop_column('auth_credentials', 'is_authenticated')
    op.alter_column('user_profile', 'id',
               existing_type=sa.UUID(),
               comment='Id representing a user within the table',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.UUID(),
               comment='The id of the user',
               existing_nullable=False)
    op.alter_column('user_profile', 'name',
               existing_type=sa.VARCHAR(length=30),
               comment='The name of the user',
               existing_nullable=False)
    op.alter_column('user_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the user was first created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the user was updated',
               existing_nullable=False)
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=False)

    op.execute("GRANT authenticated TO fastapi_user;")
    op.execute("GRANT CONNECT ON DATABASE nexttask_development TO authenticated;")
    op.execute("GRANT USAGE ON SCHEMA public TO authenticated;")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;")

    op.execute("""
                ALTER DEFAULT PRIVILEGES IN SCHEMA public
                GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;
               """)
    op.execute("""
                ALTER DEFAULT PRIVILEGES IN SCHEMA public
                GRANT USAGE, SELECT ON SEQUENCES TO authenticated;
                """)
    
    # ==================== ENABLE RLS ====================
    op.execute("ALTER TABLE user_profile ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE auth_credentials ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tasks ENABLE ROW LEVEL SECURITY")
    # ==================== RLS POLICIES ====================

    # --- user_profile ---
    op.execute("""
        CREATE POLICY user_profile_select ON user_profile
        FOR SELECT TO authenticated
        USING (user_id = current_setting('app.current_user_id', true)::uuid)
    """)
    op.execute("""
        CREATE POLICY user_profile_update ON user_profile
        FOR UPDATE TO authenticated
        USING (user_id = current_setting('app.current_user_id', true)::uuid)
    """)

    # --- auth_credentials ---
    op.execute("""
        CREATE POLICY auth_credentials_select ON auth_credentials
        FOR SELECT TO authenticated
        USING (user_id = current_setting('app.current_user_id', true)::uuid)
    """)
    op.execute("""
        CREATE POLICY auth_credentials_update ON auth_credentials
        FOR UPDATE TO authenticated
        USING (user_id = current_setting('app.current_user_id', true)::uuid)
    """)

    # --- workspaces ---
    # Owner can do everything
    op.execute("""
        CREATE POLICY workspaces_owner ON workspaces
        FOR ALL TO authenticated
        USING (owner_id = current_setting('app.current_user_id', true)::uuid)
    """)
    # Members can SELECT workspaces they belong to
    op.execute("""
        CREATE POLICY workspaces_member_select ON workspaces
        FOR SELECT TO authenticated
        USING (
            id IN (
                SELECT workspace_id FROM workspace_members
                WHERE user_id = current_setting('app.current_user_id', true)::uuid
               )
            )
    """)

    # --- workspace_members ---
    # Members can see other members in their workspace
    op.execute("""
        CREATE POLICY workspace_members_select ON workspace_members
        FOR SELECT TO authenticated
        USING (
            workspace_id IN (
                SELECT workspace_id FROM workspace_members
                WHERE user_id = current_setting('app.current_user_id', true)::uuid
            )
        )
    """)
    # Only workspace owner can insert/delete members
    op.execute("""
        CREATE POLICY workspace_members_owner ON workspace_members
        FOR ALL TO authenticated
        USING (
            workspace_id IN (
                SELECT id FROM workspaces
                WHERE owner_id = current_setting('app.current_user_id', true)::uuid
            )
        )
    """)

    # --- tasks ---
    # Workspace members can see tasks in their workspace
    op.execute("""
        CREATE POLICY tasks_select ON tasks
        FOR SELECT TO authenticated
        USING (
            workspace_id IN (
                SELECT workspace_id FROM workspace_members
                WHERE user_id = current_setting('app.current_user_id', true)::uuid)
            )
    """)
    # Only task creator can update/delete their own tasks
    op.execute("""
        CREATE POLICY tasks_owner ON tasks
        FOR ALL TO authenticated
        USING (created_by  = current_setting('app.current_user_id', true)::uuid)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ==================== DROP POLICIES ====================
    op.execute("DROP POLICY IF EXISTS user_profile_select ON user_profile")
    op.execute("DROP POLICY IF EXISTS user_profile_update ON user_profile")
    op.execute("DROP POLICY IF EXISTS auth_credentials_select ON auth_credentials")
    op.execute("DROP POLICY IF EXISTS auth_credentials_update ON auth_credentials")
    op.execute("DROP POLICY IF EXISTS workspaces_owner ON workspaces")
    op.execute("DROP POLICY IF EXISTS workspaces_member_select ON workspaces")
    op.execute("DROP POLICY IF EXISTS workspace_members_select ON workspace_members")
    op.execute("DROP POLICY IF EXISTS workspace_members_owner ON workspace_members")
    op.execute("DROP POLICY IF EXISTS tasks_select ON tasks")
    op.execute("DROP POLICY IF EXISTS tasks_owner ON tasks")

    # ==================== DISABLE RLS ====================
    op.execute("ALTER TABLE user_profile DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE auth_credentials DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE workspaces DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE workspace_members DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tasks DISABLE ROW LEVEL SECURITY")

    # ==================== DROP ROLE ====================
    op.execute("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM authenticated")
    op.execute("REVOKE CONNECT ON DATABASE nexttask_development TO authenticated")
    op.execute("DROP ROLE IF EXISTS authenticated")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=True)
    op.alter_column('user_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the user was updated',
               existing_nullable=False)
    op.alter_column('user_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the user was first created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_profile', 'name',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='The name of the user',
               existing_nullable=False)
    op.alter_column('user_profile', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='The id of the user',
               existing_nullable=False)
    op.alter_column('user_profile', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Id representing a user within the table',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.add_column('auth_credentials', sa.Column('is_authenticated', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.alter_column('auth_credentials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the user was updated',
               existing_nullable=False)
    op.alter_column('auth_credentials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the user was first created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_credentials', 'role',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='The role of the user',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('auth_credentials', 'hashed_password',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="User's password",
               existing_nullable=False)
    op.alter_column('auth_credentials', 'email',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='The email of the user',
               existing_nullable=False)
    op.alter_column('auth_credentials', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Id of the user',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('auth_credentials', 'last_login')
    op.drop_column('auth_credentials', 'email_verified')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
