name: Backend CI for Dev to Main

on:
    pull_request:
        branches: [ main ]
        paths: 
            - "backend/**"
            - ".github/workflows/backend-ci.yml"

jobs:
    test:
        runs-on: ubuntu-latest

        env:
            SECRET_KEY: ci-test-secret-key-not-real
            ENVIRONMENT: test

            # JWT
            ACCESS_TOKEN_EXPIRE_MINUTES: 30
            REFRESH_TOKEN_EXPIRE_DAYS: 7
            ALGORITHM: HS256

            # Redis
            REDIS_HOST: localhost
            REDIS_PORT: 6379
            REDIS_DB: 0
            REDIS_PASSWORD: ""

            # Postgres
            POSTGRES_HOST: localhost
            POSTGRESQL_PORT: 5432
            POSTGRES_DB: test_db
            POSTGRES_PASSWORD: test_password
            ALEMBIC_POSTGRES_USER: test_user
            FASTAPI_POSTGRES_USER: test_user
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"
                cache: "pip"
            
            - name: Install dependencies
              working-directory: backend
              run: pip install -r requirements.txt
            
            
            - name: Lint with Ruf
              working-directory: backend
              run: ruff check .
            

            - name: Run tests
              working-directory: backend
              run: pytest app/ -v

